file_paths = [
    "https://drive.google.com/file/d/14T7-4UtDj-azvs3s0U_I2FVBsKVXLbaK/view?usp=sharing",  # 1
    "https://drive.google.com/file/d/1GdUmvOH0eZu8bBYujTzpWuyCF9KHwnB7/view?usp=sharing",  # 2
    "https://drive.google.com/file/d/10mv4oV2WX1CajgOvOwtiIWmsrVc5NDGB/view?usp=sharing",  # 3
    "https://drive.google.com/file/d/1CaFw_CQ9FuDOCWjKjBRkMH337qS69rpu/view?usp=sharing",  # 4
    "https://drive.google.com/file/d/12MDQVHHf5rCEqZmF4svqbnI4fJh6Lc5o/view?usp=sharing",  # 5
    "https://drive.google.com/file/d/1e9swY5cQ24-8SVyOIq-5tJiZlYA-mGLo/view?usp=sharing",  # 6
    "https://drive.google.com/file/d/19_X0XetkAQYmysb6J8bCyqTXhJhSobl8/view?usp=sharing",  # 7
    "https://drive.google.com/file/d/1qGIM8HWW3Uwf8-mEXQNtmNOXc6NsMDor/view?usp=sharing",  # 8
    "https://drive.google.com/file/d/1mBGjKz8nLPoNXTqDzbTpkX8NTdIknpnL/view?usp=sharing",  # 9
    "https://drive.google.com/file/d/1y9Y8K9NP--JBxs__j8NtK7fZQZvFoZbp/view?usp=sharing",  # 10
    "https://drive.google.com/file/d/19RdAzgjhYDy0R6KYrVfd-ufbiGxhbdAc/view?usp=sharing",  # 11
    "https://drive.google.com/file/d/1dObmHddKXE6HPNsYfceRB3kT2WnIH8Hb/view?usp=sharing",  # 12
    "https://drive.google.com/file/d/1bI3xK_130tyTArn-0aD4DCkFsI80Y8-a/view?usp=sharing",  # 13
    "https://drive.google.com/file/d/15ELVHoWXKpk1E5kTJ0pOH29MUGrGV5aD/view?usp=sharing",  # 14
    "https://drive.google.com/file/d/1oDd99rZ7cU3OBcY8mB3FzRXrbyS6snbg/view?usp=sharing",  # 16
    "https://drive.google.com/file/d/1luCiuS5nrjHmnlfWxUhN8M7iPXY5UfzY/view?usp=sharing",  # 16
    "https://drive.google.com/file/d/1EClb7YyDsxLQa2FOEJ0MZR7D3avSRPX4/view?usp=sharing",  # 17
    "https://drive.google.com/file/d/1q3gfL9pLrGW48gNWPrYc7SbVSqPAyBAR/view?usp=sharing",  # 18
    "https://drive.google.com/file/d/12nGHrs5UA-xHU8W2fJferPs11-KhStNt/view?usp=sharing",  # 19
    "https://drive.google.com/file/d/13n6N9I6KQJEkkFy9hlMSwYVPhyaoguHj/view?usp=sharing",  # 20
    "https://drive.google.com/file/d/16BVDp4j7ocoF2Ft3OkVxM2YFEwr8MSdm/view?usp=sharing",  # 21
    "https://drive.google.com/file/d/1daRgyVRlxXnpgcP5epqjskOF8kmQELr_/view?usp=sharing",  # 22
    "https://drive.google.com/file/d/123YY-NUKMNLFPRdQZ8P8tdqhfkvBGHqj/view?usp=sharing",  # 23
    "https://drive.google.com/file/d/1kEpet_EQa3pxZhzv8o5mMYRsh-W74ymh/view?usp=sharing",  # 24
    "https://drive.google.com/file/d/14ln7QYQbAAzS4OGsb2xuckF7ZzPZJ-Wt/view?usp=sharing",  # 25
    "https://drive.google.com/file/d/1_ENg5yu9tMS696uu89FePeJ0n-UV7JpN/view?usp=sharing",  # 26
    "https://drive.google.com/file/d/1I5U-89IJCkRKojD2cmXBEARQtE4GjK8Z/view?usp=sharing",  # 27
    "https://drive.google.com/file/d/1xyLVct6gSKbFDc_S-XqXKUv6GmCdILw6/view?usp=sharing",  # 28
    "https://drive.google.com/file/d/1GozNfiERhZ3GL-LS3rzJqa0m1mjb4pKa/view?usp=sharing",  # 29
    "https://drive.google.com/file/d/1BrDehL4YKbai48kkdsgD-ZDODFFzdLac/view?usp=sharing",
]

file_names = [f'raw_2022_09_{i:02}.csv' for i in range(1, 30)]
